/**
 * Processes Form Submission and sends formatted email with Customer Details.
 * Supports dynamic content for Existing Customers vs New Referrals.
 */
function sendAutomatedLeadEmail(e) {
  const recipient = "referral@companydomain.com";
  const managerEmail = "manager@companydomain.com";

  const responses = e.namedValues;

  // Extract data from Form/Sheet
  const mode = responses['Mode'][0];
  const source = responses['Source'][0];
  const referrerName = responses['Referrer Name'][0];
  const referrerNo = responses['Referrer Number'][0];
  const referrerProject = responses['Referrer Project'][0];
  const referrerUnit = responses['Referrer Unit No'][0] || "N/A";
  const flsName = responses['FLS Name'][0];
  const flsEmail = responses['FLS Email'][0];

  // Define Referee Project here so it works for Existing Customer logic too
  const refereeProject = responses['Referree Project'][0] || "N/A";

  const subject = `Lead Generated by Marikannan - ${mode.toUpperCase()}`;

  // Use <br> for line breaks in HTML
  let htmlBody = `<p>Dear Referral Team,</p>`;

  if (source.toLowerCase().includes("existing")) {
    // HTML BODY FOR EXISTING CUSTOMER
    htmlBody += `<p>Please find the below customer details :</p>`;

    htmlBody += `<p><strong><u>Referrer Details:</u></strong><br>`;
    htmlBody += `<strong>Customer Name:</strong> ${referrerName}<br>`;
    htmlBody += `<strong>Project :</strong> ${referrerProject}<br>`;
    htmlBody += `<strong>Unit No :</strong> ${referrerUnit}<br>`;
    htmlBody += `<strong>Contact Number :</strong> ${referrerNo}</p>`;

    htmlBody += `<p>Customer looking for second property in <strong>${refereeProject}</strong>. Kindly tag this under existing customer and allocate this lead to <strong>${flsName}</strong>.</p>`;

  } else {
    // HTML BODY FOR NEW REFERRAL
    const refereeName = responses['Referree Name'][0];
    const refereeNo = responses['Referree Number'][0];
    const refereeProject = responses['Referree Project'][0];

    htmlBody += `<p>Please find the below lead details:</p>`;

    htmlBody += `<p><strong><u>Referrer Details:</u></strong><br>`;

    htmlBody += `<strong>Customer Name:</strong> ${referrerName}<br>`;
    htmlBody += `<strong>Project :</strong> ${referrerProject}<br>`;
    htmlBody += `<strong>Unit No :</strong> ${referrerUnit}<br>`;
    htmlBody += `<strong>Contact Number :</strong> ${referrerNo}</p>`;
    
    htmlBody += `<p><strong><u>Referee Details:</u></strong><br>`;

    htmlBody += `<strong>Customer Name:</strong> ${refereeName}<br>`;
    htmlBody += `<strong>Project :</strong> ${refereeProject}<br>`;
    htmlBody += `<strong>Contact Number :</strong> ${refereeNo}</p>`;
    
    htmlBody += `<p>Kindly tag this lead under <strong>${source}</strong> and allocate this lead to <strong>${flsName}</strong>.</p>`;
  }

  htmlBody += `<p>Regards,<br>Marikannan P<br>Automated Referral System</p>`;

  // CC List Logic
  let finalCCList = managerEmail;
  if (flsEmail && flsEmail.trim() !== "") {
    finalCCList += ", " + flsEmail;
  }

  // Send the email as HTML
  GmailApp.sendEmail(recipient, subject, "", {
    cc: finalCCList,
    htmlBody: htmlBody // This tells Gmail to render the BOLD tags
  });
}
